version: 1.0.0.{build}
branches:
  only:
  - master
skip_branch_with_pr: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore Chasm.sln
build:
  publish_nuget: true
  publish_core_console: true
  verbosity: normal
artifacts:
- path: Chasm.zip
  name: Chasm
deploy:
- provider: NuGet
  server: https://nuget.pkg.github.com/VoyagerChasm/index.json
  api_key:
    secure: v1nzQdEuaFF8KBuy8bQ9ko0ChkOF2VSjceZAv7TcAuv3m6bomYoj6F3E0AFnf1zS
  username:
    secure: z2zoUdsz6aT3yz6LpV1aNw==
  skip_symbols: true
  on:
    branch: master